//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DataService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Admin.DataService.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись удалена ранее другим пользователем.
        /// </summary>
        internal static string AnotherUserDeleteRecordConstraintMsg {
            get {
                return ResourceManager.GetString("AnotherUserDeleteRecordConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апрель.
        /// </summary>
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Август.
        /// </summary>
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другой пользователь изменил состояние записи. Требуется обновить журнал.
        /// </summary>
        internal static string ConcurrencyConstraintMsg {
            get {
                return ResourceManager.GetString("ConcurrencyConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для совершения операции требуется выбрать корреспондента.
        /// </summary>
        internal static string CorrespondentUserConstraintMsg {
            get {
                return ResourceManager.GetString("CorrespondentUserConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата должна быть не меньше текущей {0:dd.MM.yyyy HH:mm}.
        /// </summary>
        internal static string DataMinConstraintMsg {
            get {
                return ResourceManager.GetString("DataMinConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Декабрь.
        /// </summary>
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верный формат E-mail.
        /// </summary>
        internal static string EmailConstraintMsg {
            get {
                return ResourceManager.GetString("EmailConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не должно быть пустым.
        /// </summary>
        internal static string EmptyConstraintMsg {
            get {
                return ResourceManager.GetString("EmptyConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тело файла не может быть пустым.
        /// </summary>
        internal static string EmptyFileBodyConstraintMsg {
            get {
                return ResourceManager.GetString("EmptyFileBodyConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя прикрепить пустой файл.
        /// </summary>
        internal static string EmptyFileConstraintMsg {
            get {
                return ResourceManager.GetString("EmptyFileConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя файла не может быть пустым.
        /// </summary>
        internal static string EmptyFileNameConstraintMsg {
            get {
                return ResourceManager.GetString("EmptyFileNameConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Февраль.
        /// </summary>
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат поля должен быть {0}.
        /// </summary>
        internal static string FormatPropConstraintMsg {
            get {
                return ResourceManager.GetString("FormatPropConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно заполненные поля формы.
        /// </summary>
        internal static string GeneralConstraintMsg {
            get {
                return ResourceManager.GetString("GeneralConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Январь.
        /// </summary>
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Июль.
        /// </summary>
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Июнь.
        /// </summary>
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина поля ({0}) не должна превышать {1} символов.
        /// </summary>
        internal static string LengthMaxConstraintMsg {
            get {
                return ResourceManager.GetString("LengthMaxConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина поля ({0}) не должна быть меньше {1} символов.
        /// </summary>
        internal static string LengthMinConstraintMsg {
            get {
                return ResourceManager.GetString("LengthMinConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В день можно подать заявок не более {0} .
        /// </summary>
        internal static string LimitRequestCountConstraintMsg {
            get {
                return ResourceManager.GetString("LimitRequestCountConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Март.
        /// </summary>
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя файла не может превышать {0} символов [{1}].
        /// </summary>
        internal static string MaxFileNameConstraintMsg {
            get {
                return ResourceManager.GetString("MaxFileNameConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевышено макс. количество файлов ({0}), которые можно прикреплять к заявке.
        /// </summary>
        internal static string MaxRequestFileCountConstraintMsg {
            get {
                return ResourceManager.GetString("MaxRequestFileCountConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышен макс. размер файла ({0} Кб), который можно прикреплять к заявке [{1}].
        /// </summary>
        internal static string MaxRequestFileSizeConstraintMsg {
            get {
                return ResourceManager.GetString("MaxRequestFileSizeConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Май.
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки можно подавать с интервалом не менее {0} мин..
        /// </summary>
        internal static string MinIntervalRequestConstraintMsg {
            get {
                return ResourceManager.GetString("MinIntervalRequestConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая дата окончания {0} не может быть раньше текущей даты {1}.
        /// </summary>
        internal static string NewDeadLineDateConstraintMsg {
            get {
                return ResourceManager.GetString("NewDeadLineDateConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные не найдены. Возможно, запись была удалена другим пользователеи.
        /// </summary>
        internal static string NoDataFoundMsg {
            get {
                return ResourceManager.GetString("NoDataFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не кириллический символ {0} на позиции {1}.
        /// </summary>
        internal static string NotCyrillicConstraintMsg {
            get {
                return ResourceManager.GetString("NotCyrillicConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На стороне сервера возникла необработанная ошибка.
        /// </summary>
        internal static string NotHandledExceptionMsg {
            get {
                return ResourceManager.GetString("NotHandledExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ноябрь.
        /// </summary>
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верный формат данных: свойство {0} не должно быть null.
        /// </summary>
        internal static string NullPropConstraintMsg {
            get {
                return ResourceManager.GetString("NullPropConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Октябрь.
        /// </summary>
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только владелец профиля может удалить запись.
        /// </summary>
        internal static string OnlyOwnerEmployeeObjectCanDeleteRecordConstraintMsg {
            get {
                return ResourceManager.GetString("OnlyOwnerEmployeeObjectCanDeleteRecordConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивную заявку №{0} нельзя редактировать/удалять.
        /// </summary>
        internal static string RequesArchConstraintMsg {
            get {
                return ResourceManager.GetString("RequesArchConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка №{0} уже принята в работу Исполнителем. Редактирование/удаление запрещено.
        /// </summary>
        internal static string RequestAcceptConstraintMsg {
            get {
                return ResourceManager.GetString("RequestAcceptConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        internal static string RequiredConstraintMsg {
            get {
                return ResourceManager.GetString("RequiredConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сентябрь.
        /// </summary>
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суперпользователь не может быть удален.
        /// </summary>
        internal static string SuperUserDeleteMsg {
            get {
                return ResourceManager.GetString("SuperUserDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование суперпользователя запрещено.
        /// </summary>
        internal static string SuperUserUpdateMsg {
            get {
                return ResourceManager.GetString("SuperUserUpdateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля должно быть уникальным.
        /// </summary>
        internal static string UniqueConstraintMsg {
            get {
                return ResourceManager.GetString("UniqueConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другой пользователь зарегистрирован в системе с этим E-mail. Используйте другой E-mail.
        /// </summary>
        internal static string UniqueEmailConstraintMsg {
            get {
                return ResourceManager.GetString("UniqueEmailConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект уже присутствует в профиле заявителя.
        /// </summary>
        internal static string UniqueEmployeeObjectConstraintMsg {
            get {
                return ResourceManager.GetString("UniqueEmployeeObjectConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верный формат URL.
        /// </summary>
        internal static string URLConstraintMsg {
            get {
                return ResourceManager.GetString("URLConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля ({0}) не должно превышать {1}.
        /// </summary>
        internal static string ValueMaxConstraintMsg {
            get {
                return ResourceManager.GetString("ValueMaxConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля должно быть неотрицательным.
        /// </summary>
        internal static string ValueNonNegativeConstraintMsg {
            get {
                return ResourceManager.GetString("ValueNonNegativeConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля должно быть положительным.
        /// </summary>
        internal static string ValuePositiveConstraintMsg {
            get {
                return ResourceManager.GetString("ValuePositiveConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не возможно определить исполнителя.
        /// </summary>
        internal static string WorkerNotDefinedConstraintMsg {
            get {
                return ResourceManager.GetString("WorkerNotDefinedConstraintMsg", resourceCulture);
            }
        }
    }
}
