//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Admin.WebApp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Action_Add {
            get {
                return ResourceManager.GetString("Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить файлы.
        /// </summary>
        public static string Action_AddFile {
            get {
                return ResourceManager.GetString("Action_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить ПО.
        /// </summary>
        public static string Action_AddIS {
            get {
                return ResourceManager.GetString("Action_AddIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить оборудование.
        /// </summary>
        public static string Action_AddTO {
            get {
                return ResourceManager.GetString("Action_AddTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить фильтр.
        /// </summary>
        public static string Action_ApplyFilter {
            get {
                return ResourceManager.GetString("Action_ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить заявку.
        /// </summary>
        public static string Action_DeleteRequest {
            get {
                return ResourceManager.GetString("Action_DeleteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Action_Edit {
            get {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать заявку.
        /// </summary>
        public static string Action_EditRequest {
            get {
                return ResourceManager.GetString("Action_EditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Action_Login {
            get {
                return ResourceManager.GetString("Action_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая заявка.
        /// </summary>
        public static string Action_NewRequest {
            get {
                return ResourceManager.GetString("Action_NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить пароль.
        /// </summary>
        public static string Action_RecoveryPassword {
            get {
                return ResourceManager.GetString("Action_RecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string Action_Register {
            get {
                return ResourceManager.GetString("Action_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить фильтр.
        /// </summary>
        public static string Action_ResetFilter {
            get {
                return ResourceManager.GetString("Action_ResetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string Action_Select {
            get {
                return ResourceManager.GetString("Action_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевести.
        /// </summary>
        public static string Action_Transfer {
            get {
                return ResourceManager.GetString("Action_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Action_Update {
            get {
                return ResourceManager.GetString("Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Action_Сancel {
            get {
                return ResourceManager.GetString("Action_Сancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не допустимый тип файла.
        /// </summary>
        public static string ErrorMessage_AcceptFileTypesConstraint {
            get {
                return ResourceManager.GetString("ErrorMessage_AcceptFileTypesConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и его подтверждение не совпадают.
        /// </summary>
        public static string ErrorMessage_ConfirmPassword {
            get {
                return ResourceManager.GetString("ErrorMessage_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышен максимальный размер файла {0} KB.
        /// </summary>
        public static string ErrorMessage_MaxFileSizeConstraint {
            get {
                return ResourceManager.GetString("ErrorMessage_MaxFileSizeConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышено допустимое количество файлов.
        /// </summary>
        public static string ErrorMessage_MaxNumberOfFilesConstraint {
            get {
                return ResourceManager.GetString("ErrorMessage_MaxNumberOfFilesConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком маленький размер файла.
        /// </summary>
        public static string ErrorMessage_MinFileSizeConstraint {
            get {
                return ResourceManager.GetString("ErrorMessage_MinFileSizeConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля {0} должно содержать не менее {2} и не более {1} символов.
        /// </summary>
        public static string ErrorMessage_StringLengthConstraint {
            get {
                return ResourceManager.GetString("ErrorMessage_StringLengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не подтвердили, что Вы не робот.
        /// </summary>
        public static string InvalidReCaptcha {
            get {
                return ResourceManager.GetString("InvalidReCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление информационной системы/ПО.
        /// </summary>
        public static string Label_AddIS {
            get {
                return ResourceManager.GetString("Label_AddIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оборудование.
        /// </summary>
        public static string Label_AddTO {
            get {
                return ResourceManager.GetString("Label_AddTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        public static string Label_Amount {
            get {
                return ResourceManager.GetString("Label_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив.
        /// </summary>
        public static string Label_Archive {
            get {
                return ResourceManager.GetString("Label_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кабинет.
        /// </summary>
        public static string Label_Cabinet {
            get {
                return ResourceManager.GetString("Label_Cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Label_ChooseLang {
            get {
                return ResourceManager.GetString("Label_ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корреспондент.
        /// </summary>
        public static string Label_Correspondent {
            get {
                return ResourceManager.GetString("Label_Correspondent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания.
        /// </summary>
        public static string Label_DateEndPlan {
            get {
                return ResourceManager.GetString("Label_DateEndPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата/время.
        /// </summary>
        public static string Label_DateTime {
            get {
                return ResourceManager.GetString("Label_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание проблемы.
        /// </summary>
        public static string Label_DescriptionProblem {
            get {
                return ResourceManager.GetString("Label_DescriptionProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокировано.
        /// </summary>
        public static string Label_Disabled {
            get {
                return ResourceManager.GetString("Label_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявитель.
        /// </summary>
        public static string Label_Employee {
            get {
                return ResourceManager.GetString("Label_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата события.
        /// </summary>
        public static string Label_EventDateEvent {
            get {
                return ResourceManager.GetString("Label_EventDateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примечание.
        /// </summary>
        public static string Label_EventNote {
            get {
                return ResourceManager.GetString("Label_EventNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие.
        /// </summary>
        public static string Label_EventStatusName {
            get {
                return ResourceManager.GetString("Label_EventStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Label_FM {
            get {
                return ResourceManager.GetString("Label_FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не помните пароль?.
        /// </summary>
        public static string Label_ForgetPassword {
            get {
                return ResourceManager.GetString("Label_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От.
        /// </summary>
        public static string Label_From {
            get {
                return ResourceManager.GetString("Label_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип оборудования (принтер, монитор, сканер и т.п.).
        /// </summary>
        public static string Label_HardType {
            get {
                return ResourceManager.GetString("Label_HardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Label_IM {
            get {
                return ResourceManager.GetString("Label_IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информационная система/ПО.
        /// </summary>
        public static string Label_IS {
            get {
                return ResourceManager.GetString("Label_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин или E-mail.
        /// </summary>
        public static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Label_Logout {
            get {
                return ResourceManager.GetString("Label_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производитель (SONY, SAMSUNG  и т.п.).
        /// </summary>
        public static string Label_Manufacturer {
            get {
                return ResourceManager.GetString("Label_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        public static string Label_Model {
            get {
                return ResourceManager.GetString("Label_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примечание.
        /// </summary>
        public static string Label_Note {
            get {
                return ResourceManager.GetString("Label_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект заявки.
        /// </summary>
        public static string Label_ObjectName {
            get {
                return ResourceManager.GetString("Label_ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид работ (определяет исполнителя работ).
        /// </summary>
        public static string Label_ObjectType {
            get {
                return ResourceManager.GetString("Label_ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to из.
        /// </summary>
        public static string Label_Of {
            get {
                return ResourceManager.GetString("Label_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация.
        /// </summary>
        public static string Label_Organization {
            get {
                return ResourceManager.GetString("Label_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string Label_OT {
            get {
                return ResourceManager.GetString("Label_OT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № телефона.
        /// </summary>
        public static string Label_Phone {
            get {
                return ResourceManager.GetString("Label_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должность.
        /// </summary>
        public static string Label_Post {
            get {
                return ResourceManager.GetString("Label_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string Label_RememberMe {
            get {
                return ResourceManager.GetString("Label_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка.
        /// </summary>
        public static string Label_Request {
            get {
                return ResourceManager.GetString("Label_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата подачи.
        /// </summary>
        public static string Label_RequestDate {
            get {
                return ResourceManager.GetString("Label_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № заявки.
        /// </summary>
        public static string Label_RequestNumber {
            get {
                return ResourceManager.GetString("Label_RequestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние.
        /// </summary>
        public static string Label_StatusName {
            get {
                return ResourceManager.GetString("Label_StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получать рассылку на E-mail.
        /// </summary>
        public static string Label_Subscribe {
            get {
                return ResourceManager.GetString("Label_Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        public static string Label_To {
            get {
                return ResourceManager.GetString("Label_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего записей.
        /// </summary>
        public static string Label_TotalCount {
            get {
                return ResourceManager.GetString("Label_TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кому.
        /// </summary>
        public static string Label_ToWhom {
            get {
                return ResourceManager.GetString("Label_ToWhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string Label_User {
            get {
                return ResourceManager.GetString("Label_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип пользователя.
        /// </summary>
        public static string Label_UserType {
            get {
                return ResourceManager.GetString("Label_UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель.
        /// </summary>
        public static string Label_Worker {
            get {
                return ResourceManager.GetString("Label_Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип работ.
        /// </summary>
        public static string Label_WorkTypeName {
            get {
                return ResourceManager.GetString("Label_WorkTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подать заявку.
        /// </summary>
        public static string Menu_Request {
            get {
                return ResourceManager.GetString("Menu_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои заявки.
        /// </summary>
        public static string Menu_RequestHistory {
            get {
                return ResourceManager.GetString("Menu_RequestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Menu_Users {
            get {
                return ResourceManager.GetString("Menu_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждаете удаление?.
        /// </summary>
        public static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанные E-mail не зарегистрирован в системе.
        /// </summary>
        public static string Message_EmailNotRegitered {
            get {
                return ResourceManager.GetString("Message_EmailNotRegitered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное имя пользователя или пароль.
        /// </summary>
        public static string Message_LoginError {
            get {
                return ResourceManager.GetString("Message_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание новой заявки.
        /// </summary>
        public static string Message_NewRequestCreate {
            get {
                return ResourceManager.GetString("Message_NewRequestCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записей не найдено.
        /// </summary>
        public static string Message_NotFound {
            get {
                return ResourceManager.GetString("Message_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка успешно сохранена.
        /// </summary>
        public static string Message_RequestComplete {
            get {
                return ResourceManager.GetString("Message_RequestComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование заявки.
        /// </summary>
        public static string Message_RequestEdit {
            get {
                return ResourceManager.GetString("Message_RequestEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите сумму.
        /// </summary>
        public static string Placeholder_Amount {
            get {
                return ResourceManager.GetString("Placeholder_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Email.
        /// </summary>
        public static string Placeholder_Email {
            get {
                return ResourceManager.GetString("Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите сотрудника.
        /// </summary>
        public static string Placeholder_EmployeeName {
            get {
                return ResourceManager.GetString("Placeholder_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите объект заявки сотрудника (сначала выберите сотрудника).
        /// </summary>
        public static string Placeholder_EmployeeObjectName {
            get {
                return ResourceManager.GetString("Placeholder_EmployeeObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите объект заявки сотрудника.
        /// </summary>
        public static string Placeholder_EmployeeObjectName2 {
            get {
                return ResourceManager.GetString("Placeholder_EmployeeObjectName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите или введите тип оборудования.
        /// </summary>
        public static string Placeholder_HardType {
            get {
                return ResourceManager.GetString("Placeholder_HardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите информационную систему/ПО.
        /// </summary>
        public static string Placeholder_IS {
            get {
                return ResourceManager.GetString("Placeholder_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите или введите производителя.
        /// </summary>
        public static string Placeholder_Manufacturer {
            get {
                return ResourceManager.GetString("Placeholder_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите или введите модель.
        /// </summary>
        public static string Placeholder_Model {
            get {
                return ResourceManager.GetString("Placeholder_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя.
        /// </summary>
        public static string Placeholder_Name {
            get {
                return ResourceManager.GetString("Placeholder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите объект заявки (задается в {0}).
        /// </summary>
        public static string Placeholder_ObjectName {
            get {
                return ResourceManager.GetString("Placeholder_ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите организацию.
        /// </summary>
        public static string Placeholder_Organization {
            get {
                return ResourceManager.GetString("Placeholder_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string Placeholder_Password {
            get {
                return ResourceManager.GetString("Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввведите или выберите должность.
        /// </summary>
        public static string Placeholder_Post {
            get {
                return ResourceManager.GetString("Placeholder_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввведите имя пользователя.
        /// </summary>
        public static string Placeholder_UserName {
            get {
                return ResourceManager.GetString("Placeholder_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для подачи заявки требуется заполнить данные.
        /// </summary>
        public static string Text_AllDataAreRequiredToApply {
            get {
                return ResourceManager.GetString("Text_AllDataAreRequiredToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a target=&apos;_blank&apos; href=&apos;http://google.com&apos;&gt;ООО &quot;OOO&quot;&lt;/a&gt;.
        /// </summary>
        public static string Text_Copyright {
            get {
                return ResourceManager.GetString("Text_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во переносов.
        /// </summary>
        public static string Text_CountCorrectionDateEndPlan {
            get {
                return ResourceManager.GetString("Text_CountCorrectionDateEndPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество заявок, требующих подтверждения готовности.
        /// </summary>
        public static string Text_CountRequestRequiresConfirmation {
            get {
                return ResourceManager.GetString("Text_CountRequestRequiresConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование.
        /// </summary>
        public static string Text_EditRecord {
            get {
                return ResourceManager.GetString("Text_EditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо полностью заполнить форму.
        /// </summary>
        public static string Text_ItIsNecessaryToFillInTheFormCompletely {
            get {
                return ResourceManager.GetString("Text_ItIsNecessaryToFillInTheFormCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руководство пользователя.
        /// </summary>
        public static string Text_ManualUrl {
            get {
                return ResourceManager.GetString("Text_ManualUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая запись.
        /// </summary>
        public static string Text_NewRecord {
            get {
                return ResourceManager.GetString("Text_NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствуют обслуживаемые организации. Добавление заявок не возможно.
        /// </summary>
        public static string Text_NotAllowableEmployee {
            get {
                return ResourceManager.GetString("Text_NotAllowableEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновите страницу, нажав Ctrl + F5.
        /// </summary>
        public static string Text_PressCtrlF5 {
            get {
                return ResourceManager.GetString("Text_PressCtrlF5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль направлен на указанный E-mail.
        /// </summary>
        public static string Text_RecoveredPassword {
            get {
                return ResourceManager.GetString("Text_RecoveredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите адрес E-mail, с которым вы были зарегестрированы в системе. Пароль будет отправлен на этот адрес электронной почты.
        /// </summary>
        public static string Text_RecoveryPassword {
            get {
                return ResourceManager.GetString("Text_RecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль от личного кабинета {0}.
        /// </summary>
        public static string Text_RecoveryPasswordSubject {
            get {
                return ResourceManager.GetString("Text_RecoveryPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация в личном кабинете {0}.
        /// </summary>
        public static string Text_RegisterNow {
            get {
                return ResourceManager.GetString("Text_RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Text_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Text_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соглашение об уровне сервиса.
        /// </summary>
        public static string Text_ServiceLevelAgreementUrl {
            get {
                return ResourceManager.GetString("Text_ServiceLevelAgreementUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Техническая поддержка.
        /// </summary>
        public static string Text_TechSupportPhones {
            get {
                return ResourceManager.GetString("Text_TechSupportPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо добавить хотя бы один объект, на который будет подаваться заявка, в форму.
        /// </summary>
        public static string Text_YouMustAddAtLeastOneObject {
            get {
                return ResourceManager.GetString("Text_YouMustAddAtLeastOneObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать заявку.
        /// </summary>
        public static string Title_CreateRequest {
            get {
                return ResourceManager.GetString("Title_CreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать заявку.
        /// </summary>
        public static string Title_EditRequest {
            get {
                return ResourceManager.GetString("Title_EditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Title_Refresh {
            get {
                return ResourceManager.GetString("Title_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История событий заявки.
        /// </summary>
        public static string Title_RequestHistory {
            get {
                return ResourceManager.GetString("Title_RequestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перенос срока.
        /// </summary>
        public static string Title_Transfer {
            get {
                return ResourceManager.GetString("Title_Transfer", resourceCulture);
            }
        }
    }
}
